name: build and execute Python script

on:[push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
       name: Checkout code

      -name: Set up Python 3.8
       uses: actions/setup-python@v5
       with:
         python-version:3.8
      -name: Install dependencies
       shell: bash
       run:
         pip install fastapi locust pytest uvico
      -name: Execution de pytest
       run : pytest
